name: Node.js Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # 可以指定具体版本，也可以用 '16.x' 以满足小于等于16的要求

      - name: Verify Node.js version
        run: |
          if [ "$(node -v | cut -c 2-3)" -gt "16" ]; then
            echo "Node.js version must be <= 16"
            exit 1
          fi

      - name: Install dependencies
        working-directory: jeepay-ui-manager
        run: npm install

      - name: Build project
        working-directory: jeepay-ui-manager
        run: npm run build
